### ISSUE TITLE
Your Book is Fantastic

### ISSUE THREAD

**Issue by jasonzoladz** [sbarski/serverless-architectures-aws#4]
I've worked through the first 7 chapters of your book (in TypeScript, because JS :scream:) and it's among the finest practical tech books I've ever read.  Well-organized; detailed and clear; reinforces concepts regularly; good exercises.

Really, kudos.  Amazon should send you a cut of each reader's AWS bill, as I'll be utilizing a lot more AWS computing power as a result of reading your book.

**Comment by sbarski** [comment]
Thank you so much for your feedback @jasonzoladz. It's great to receive something like this :)

Glad that you are enjoying the book!
